### PR TITLE
 Use split with regex for ls output 

### LINKED ISSUE #288: [Bug] Backup fails if some filenames contain two consecutive spaces
**Description**
Backing up the F-Droid store app with data fails if a specific APK file is in the app data.

**Steps To Reproduce**

1. Install F-Droid as app
2. Download this app through the store (does not need to be installed): 
https://f-droid.org/de/packages/com.simplemobiletools.gallery.pro/ 
3. Try to backup F-Droid with data, it fails with the error below

I tried many other apps/APKs and could not find any others that cause this error... but with this gallery app it happens reproducibly.

**Logcat**

```
01-19 01:04:01.939 25050 26844 I e       : Backing up: org.fdroid.fdroid [F-Droid]
01-19 01:04:01.940 25050 26736 D OpenGLRenderer: endAllActiveAnimators on 0x7cf82b2100 (RippleDrawable) with handle 0x7cc5a4bd80
01-19 01:04:01.947 25050 25050 W UiThreadStatement: Already on the UI thread, this method should not be called from the main application thread
01-19 01:04:01.985 25050 26844 I e       : Schedule{packageName=org.fdroid.fdroid, appMetaInfo=m.a.a.l.c@9e75e08, appUri=content://com.android.externalstorage.documents/tree/primary%3AOABX/document/primary%3AOABX%2Forg.fdroid.fdroid, storageStats=android.app.usage.StorageStats@859a9a1, packageInfo={true, /data/app/org.fdroid.fdroid-Cegpaojbcu_psX7BMXIFrw==/base.apk, /data/user/0/org.fdroid.fdroid, /data/user_de/0/org.fdroid.fdroid}, backupHistory=[BackupItem{ packageName="org.fdroid.fdroid", packageLabel="F-Droid", backupDate="2021-01-19T01:02:49.347" }]}: Backing up package
01-19 01:04:01.986 25050 26844 I a       : [org.fdroid.fdroid] Backup package apks
01-19 01:04:01.986 25050 26844 D a       : [org.fdroid.fdroid] The app is a normal apk
01-19 01:04:01.986 25050 26844 D a       : [org.fdroid.fdroid] Backing up package (1 apks: base.apk)
01-19 01:04:02.044 25050 26844 I e       : Schedule{packageName=org.fdroid.fdroid, appMetaInfo=m.a.a.l.c@9e75e08, appUri=content://com.android.externalstorage.documents/tree/primary%3AOABX/document/primary%3AOABX%2Forg.fdroid.fdroid, storageStats=android.app.usage.StorageStats@859a9a1, packageInfo={true, /data/app/org.fdroid.fdroid-Cegpaojbcu_psX7BMXIFrw==/base.apk, /data/user/0/org.fdroid.fdroid, /data/user_de/0/org.fdroid.fdroid}, backupHistory=[BackupItem{ packageName="org.fdroid.fdroid", packageLabel="F-Droid", backupDate="2021-01-19T01:02:49.347" }]}: Backing up data
01-19 01:04:02.044 25050 26844 I a       : [org.fdroid.fdroid] Starting data backup
01-19 01:04:02.044 25050 26844 D a       : Running Command: toybox ls -All "/data/user/0/org.fdroid.fdroid"
01-19 01:04:02.070 25050 26844 D a       : Command(s) '[Ljava.lang.String;@a9852b4' ended with 0
01-19 01:04:02.071 25050 26844 D a       : Running Command: toybox ls -All "/data/user/0/org.fdroid.fdroid/app_ACRA-approved"
01-19 01:04:02.096 25050 26844 D a       : Command(s) '[Ljava.lang.String;@7463edd' ended with 0
01-19 01:04:02.096 25050 26844 D a       : Running Command: toybox ls -All "/data/user/0/org.fdroid.fdroid/app_ACRA-unapproved"
01-19 01:04:02.124 25050 26844 D a       : Command(s) '[Ljava.lang.String;@bfe4a52' ended with 0
01-19 01:04:02.124 25050 26844 D a       : Running Command: toybox ls -All "/data/user/0/org.fdroid.fdroid/app_keystore"
01-19 01:04:02.137 25050 26844 D a       : Command(s) '[Ljava.lang.String;@356d123' ended with 0
01-19 01:04:02.137 25050 26844 D a       : Running Command: toybox ls -All "/data/user/0/org.fdroid.fdroid/databases"
01-19 01:04:02.149 25050 26844 D a       : Command(s) '[Ljava.lang.String;@3c1e620' ended with 0
01-19 01:04:02.149 25050 26844 D a       : Running Command: toybox ls -All "/data/user/0/org.fdroid.fdroid/files"
01-19 01:04:02.163 25050 26844 D a       : Command(s) '[Ljava.lang.String;@a6cebd9' ended with 0
01-19 01:04:02.163 25050 26844 D a       : Running Command: toybox ls -All "/data/user/0/org.fdroid.fdroid/files/FDROID"
01-19 01:04:02.177 25050 26844 D a       : Command(s) '[Ljava.lang.String;@312b99e' ended with 0
01-19 01:04:02.179 25050 26844 D a       : Running Command: toybox ls -All "/data/user/0/org.fdroid.fdroid/files/FDROID/REPO"
01-19 01:04:02.209 25050 26844 D a       : Command(s) '[Ljava.lang.String;@1bb5c7f' ended with 0
01-19 01:04:02.210 25050 26844 D a       : Running Command: toybox ls -All "/data/user/0/org.fdroid.fdroid/files/fdroid"
01-19 01:04:02.237 25050 26844 D a       : Command(s) '[Ljava.lang.String;@c2f444c' ended with 0
01-19 01:04:02.238 25050 26844 D a       : Running Command: toybox ls -All "/data/user/0/org.fdroid.fdroid/files/fdroid/repo"
01-19 01:04:02.257 25050 26844 D a       : Command(s) '[Ljava.lang.String;@5b76c95' ended with 0
01-19 01:04:02.258 25050 26844 D a       : Running Command: toybox ls -All "/data/user/0/org.fdroid.fdroid/files/fdroid/repo/icons"
01-19 01:04:02.271 25050 26844 D a       : Command(s) '[Ljava.lang.String;@26cd1aa' ended with 0
01-19 01:04:02.271 25050 26844 D a       : Running Command: toybox ls -All "/data/user/0/org.fdroid.fdroid/shared_prefs"
01-19 01:04:02.284 25050 26844 D a       : Command(s) '[Ljava.lang.String;@3b3419b' ended with 0
01-19 01:04:02.285 25050 26844 I a       : Backing up data got 43 files to backup
01-19 01:04:02.285 25050 26844 I a       : Creating data backup
01-19 01:04:02.298 25050 26844 D a       : Adding app_ACRA-approved to archive (filesize: 0)
01-19 01:04:02.298 25050 26844 D a       : Adding app_ACRA-unapproved to archive (filesize: 0)
01-19 01:04:02.298 25050 26844 D a       : Adding app_keystore to archive (filesize: 0)
01-19 01:04:02.299 25050 26844 D a       : Adding app_keystore/kerplapp.bks to archive (filesize: 2091)
01-19 01:04:02.340 25050 26844 D a       : Adding databases to archive (filesize: 0)
01-19 01:04:02.340 25050 26844 D a       : Adding databases/fdroid to archive (filesize: 8658944)
01-19 01:04:02.999 25050 26844 D a       : Adding databases/fdroid-journal to archive (filesize: 0)
01-19 01:04:03.022 25050 26844 D a       : Adding files to archive (filesize: 0)
01-19 01:04:03.022 25050 26844 D a       : Adding files/Aurora Store-3.2.8.apk to archive (filesize: 4597548)
01-19 01:04:03.409 25050 26844 D a       : Adding files/DAVx-3.3.7-ose.apk to archive (filesize: 9747265)
01-19 01:04:04.195 25050 26844 D a       : Adding files/FDROID to archive (filesize: 0)
01-19 01:04:04.195 25050 26844 D a       : Adding files/Schlichte Galerie Pro - Foto Manager Editor-6.18.0.apk to archive (filesize: 15951095)
01-19 01:04:04.205 25050 26844 D a       : Done compressing. Closing data.tar.gz
01-19 01:04:04.205 25050 26844 E a       : java.io.IOException occurred on data backup: java.io.IOException: Entry 'files/Schlichte Galerie Pro - Foto Manager Editor-6.18.0.apk' closed at '0' before the '15951095' bytes specified in the header were written
01-19 01:04:04.205 25050 26844 E e       : Backup failed due to a: java.io.IOException occurred on data backup: java.io.IOException: Entry 'files/Schlichte Galerie Pro - Foto Manager Editor-6.18.0.apk' closed at '0' before the '15951095' bytes specified in the header were written
```

```
127|davinci:/data/data/org.fdroid.fdroid/files # ls -All
-rw------- 1 u0_a247 u0_a247  4597548 2021-01-19 01:02:39.000000000 +0100 Aurora\ Store-3.2.8.apk
drwx------ 3 u0_a247 u0_a247     3488 2021-01-19 00:56:56.797387120 +0100 FDROID
-rw------- 1 u0_a247 u0_a247 15951095 2021-01-19 01:03:29.000000000 +0100 Schlichte\ Galerie\ Pro\ -\ Foto\ Manager\ \ Editor-6.18.0.apk
-rw------- 1 u0_a247 u0_a247 42411711 2021-01-19 00:59:28.000000000 +0100 Tasks.org\ Open-Source-Aufgabenlisten\ und\ Erinneru-11.2.1.apk
```
I don't see a difference to the other .apk files, but the backup works if I just delete `Schlichte\ Galerie\ Pro\ -\ Foto\ Manager\ \ Editor-6.18.0.apk`, very strange.

**System Information:**

- Device: Mi 9T
- Android Version: 10
- ROM: Havoc OS, Magisk 21.4
- App's Version: 5.0.0

### PR DESCRIPTION
**Pull request by Jakeler**
The regex `\s+` matches one or more spaces directly, so there are no empty tokens generated.
Additional filtering and error prone recombining is therefore not necessary anymore.
This makes the code simpler and also more reliable in my testing. 
Fixes #288.

Also I have added adjusted/extended ShellHandler tests, based on #291 from @hg42.

### CODE REVIEW

**Comment by hg42** [comment]
please accept this PR...it's perfect

well, that said, I wonder why it is called `fromLs>>>O<<<Output`, may be a typo, or something like O=out, E=err?
I think, it could be the right time to rename it to `fromLsOutput`...

**Review by hg42 — APPROVED** [review]
I tested the PR in the debugger

File: app/src/main/java/com/machiav3lli/backup/handler/ShellHandler.kt [hunk 1]
```diff
@@ -58,7 +58,7 @@ class ShellHandler {
         val result = shellResult.out.asSequence()
                 .filter { line: String -> line.isNotEmpty() }
                 .filter { line: String -> !line.startsWith("total") }
-                .filter { line: String -> splitWithoutEmptyValues(line, " ", 0).size > 8 }
+                .filter { line: String -> line.split(Regex("""\s+"""), 0).size > 8 }
                 .map { line: String -> FileInfo.fromLsOOutput(line, relativeParent, path) }
```
Comment (hg42) [inline app/src/main/java/com/machiav3lli/backup/handler/ShellHandler.kt:62]: eventually we could also rename the function to `fromLsOutput`

**Comment by hg42** [comment]
sorry, it's the first time I use the review functionality...I always implied that you have to be a maintainer for that
